version: '3'

networks:
  mynetwork:
    driver: bridge

services:
   java_backend_app:
     build: .
     ports:
      - "8888:8888"
     depends_on:
       - postgres_db
     networks:
       - mynetwork
     environment:
       - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/lottery
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: lottery
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - mynetwork

volumes:
  pgdata:
